name: Deploy develop to GitHub Pages

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v3

      # すでにリポジトリ内にある dist フォルダを develop フォルダに退避
      - name: Move dist to develop folder
        run: |
          mkdir deploy
          mkdir deploy/develop
          cp -r dist/* deploy/develop/

      # デプロイを実行
      - name: Deploy to gh-pages (develop/)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./deploy
          keep_files: true